bechdel_dbt_project:
  target: dev
  outputs:
    dev:
      dataset: development
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/jdtganding0998/keys/project_service_key.json
      location: us-central1
      method: service-account
      priority: interactive
      project: data-project-3495
      threads: 4
      type: bigquery
    prod:
      dataset: production
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/jdtganding0998/keys/project_service_key.json
      location: us-central1
      method: service-account
      priority: interactive
      project: data-project-3495
      threads: 4
      type: bigquery