version: 2

sources:
  - name: staging
    database: data-projects-383009
    schema: bechdel_movies_project
    tables:
      - name: bechdel
      - name: oscars
      - name: imdb_title_basics
      - name: imdb_name_basics
      - name: imdb_title_crew

models:
  - name: imdb_title_basics_model
    description: "dbt model for splitting genres column"
    columns:
      - name: tconst
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: bechdel_transform_model
    description: "dbt model for transforming Bechdel Test movie data"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
