version: 2

sources:
  - name: staging
    database: data-projects-383009
    schema: bechdel_movies_project
    tables:
      - name: bechdel
      - name: oscars_new
      - name: imdb_title_basics_new
      - name: imdb_name_basics
      - name: imdb_title_crew
      - name: imdb_title_ratings

models:
  - name: imdb_title_basics_model
    description: "contains the transformed data from imdb_title_basics_new table"
    columns:
      - name: tconst
        description: "unique identifier of the IMDB title"
        tests:
          - unique
          - not_null
      - name: titleType
        description: "type/format of the title"
      - name: primaryTitle
        description: "the more popular title used for promotions"
      - name: originalTitle
        description: "the original title in the original language"
      - name: isAdult
        descirption: "0 if a non-adult title, 1 if an adult title"
      - name: startYear
        descripton: "release year of the title"
      - name: genre
        description: "genre of the title; original table includes up 
                      to three genres and then separated in the model"

  - name: bechdel_transform_model
    description: "model for transforming Bechdel Test movie data"
    columns:
      - name: title
        description: "the name of the movie or title"
      - name: imdbid
        description: "unique identifier of the title based on IMDB tconst"
        tests:
          - unique
          - not null
      - name: rating
        description: "Bechdel Test score of the title"
      - name: id
        decription: "unique identifier of the title within bechdeltest.com"
        tests:
          - unique
          - not null
      - name: year
        description: "release year of the title"
      - name: ratingRemark
        description: "whether the rating is passed or failed; scores of 0-2
                      are marked as failed while scores with 3 are passed"

  - name: imdb_name_basics_model
    description: "contains the transformed data from imdb_name_basics table"
    columns:
      - name: tconst
        description: "unique identifier of the IMDB title"
        tests:
          - not_null
      - name: nconst
        description: "alphanumeric unique identifier of the name/person"
      - name: primaryName
        description: "name by which the person is most often credited"
      - name: birthYear
        description: "year of birth of person in YYYY format"
      - name: primaryProfession
        description: "profession of the person; original data lists the 
                      top 3 profession"

  - name: imdb_title_crew_model
    description: "contains the transformed data from imdb_title_crew table"
    columns:
      - name: tconst
        description: "unique identifier of the IMDB title"
        tests:
          - not_null
      - name: director
        description: "director/s of the given title"
      - name: writer
        description: "writer/s of the given title"